Front end must validate data, so we don't raise error
nakhll-company/nakhll_backend pull request #185
Opened 2022-06-08 12:18 UTC by likecodingloveproblems

I am not comfortable with this solution. I doubt we must validate data on the back side.

2022-06-08 13:10 UTC, mohsenone requested changes

2022-06-08 13:10 UTC, mohsenone commented on nakhll_market/serializers.py
> +        except BaseException:
@PouryaMansouri 
```BaseException```s usually are not good solutions. Also note that, frontend can't handle this kind of error, because there are some cities with same exact name in whole country, which cause ```django.core.exceptions.MultipleObjectsReturned``` error.
I think best solution here is to replace ```name``` with ```id```, so we can make sure that ```get``` always return only one object

2022-06-08 14:35 UTC, likecodingloveproblems commented on nakhll_market/serializers.py
> +        except BaseException:
States are unique and the combination of State and BigCity is unique too, and the combination of City and BigCity is unique too. So this is not the problem.
But Milad said to me that mohsen remove some previous routes like BankAccountShopSettings and enhance ShopAllSettings to don't force to send all data and update each data that is sent

چن میترشم نامفهوم باشه متن بالا فارسیش رو هم مینویسم. میلاد گفت قبلا اینجوری بوده که فورس بوده و ی سری روت های دیگه داشتیم مثل BankAccountShopSettings برای اصلاح حساب کاربری بعد محسن اومده همین روت رو اصلاح کرده که هر دیتایی که اومد فقط همون اصلاح بشه.
من گفتم اگه توی فرایند ی جا باید حتما استان و شهرستان و شهر ست بشه چی ؟ گفت اونجا دیگه ما تو فرانت حواسمون هست. ولی من به نظرم رسید این راه حل قشنگی نیست.

2022-06-11 07:30 UTC, likecodingloveproblems commented on nakhll_market/serializers.py
> +        except BaseException:
@mohsenone

2022-06-20 09:22 UTC, mohsenone commented on nakhll_market/serializers.py
> +        except BaseException:
Please, separate serializers for create (POST) and update (PATCH)

2022-07-06 10:19 UTC, merged