fix bug
nakhll-company/nakhll_backend pull request #39
Opened 2022-05-07 07:12 UTC by PouryaMansouri

add "get_user_cart" method to "CartManager".

2022-05-07 14:20 UTC, likecodingloveproblems requested changes

2022-05-07 14:20 UTC, likecodingloveproblems commented on cart/managers.py
> +        return cart
It seems very similar to Cart _get_user_cart method, if these two have the same functionality why do they are defined twice?

2022-05-07 14:20 UTC, likecodingloveproblems commented on nakhll_market/serializers.py
> +            tags_list = []
I don't know if validating data here is correct because we name it validated_data, and this problem can occur for banners too and so on ...

2022-05-07 14:20 UTC, likecodingloveproblems commented on nakhll_market/serializers.py
> +            tags_list = []
```suggestion
tags_list: list = [x['tag'] for x in validated_data.pop('product_tags', [])]
```

2022-05-08 07:15 UTC, PouryaMansouri commented on nakhll_market/serializers.py
> +            tags_list = []
test

2022-05-08 07:20 UTC, PouryaMansouri commented on nakhll_market/serializers.py
> +            tags_list = []
test

2022-05-08 07:24 UTC, likecodingloveproblems approved these changes

2022-05-08 07:24 UTC, likecodingloveproblems commented on cart/managers.py
> +        return cart
Ok, it seems this is the result of #36
@mohsenone please take a look at this!

2022-05-08 08:05 UTC, merged