add shop fields to api
nakhll-company/nakhll_backend pull request #55
Opened 2022-05-14 06:20 UTC by PouryaMansouri

2022-05-15 08:52 UTC, likecodingloveproblems commented on nakhll_market/api.py
> +        self.check_object_permissions(request, shop)
@PouryaMansouri Django permission _classes does not check object permissions, only check Model level permissions?

2022-05-15 08:54 UTC, likecodingloveproblems commented on nakhll_market/models.py
> +        if Product.objects.filter(Title=self.Title, FK_Shop_id=self.FK_Shop_id).exist():
have you configured the styling tools mentioned in README?

2022-05-15 08:56 UTC, likecodingloveproblems commented on nakhll_market/serializers.py
> +            "City","Location"
please, `"` OR `'` NOT BOTH.
```suggestion
            'bank_account', 'social_media', 'Description', 'FK_ShopManager', 'state', 'BigCity',
            'City', 'Location'

2022-05-15 08:57 UTC, likecodingloveproblems requested changes
please config styling options

2022-05-15 09:10 UTC, PouryaMansouri commented on nakhll_market/api.py
> +        self.check_object_permissions(request, shop)
we check object permission in line 690.

2022-05-15 09:11 UTC, PouryaMansouri commented on nakhll_market/api.py
> +        self.check_object_permissions(request, shop)
I just follow the code in other views.

2022-05-15 09:12 UTC, PouryaMansouri commented on nakhll_market/api.py
> +        self.check_object_permissions(request, shop)
I 

> @PouryaMansouri Django permission _classes does not check object permissions, only check Model level permissions?

I think Django permission can check everything.
BUT in prefer to follow the code.

2022-05-15 09:16 UTC, PouryaMansouri commented on nakhll_market/models.py
> +        if Product.objects.filter(Title=self.Title, FK_Shop_id=self.FK_Shop_id).exist():
> have you configured the styling tools mentioned in README?

I use Pycharm's plugins to reformat the code.
This style was suggested with these plugins. ( Pylint, pep8 and etc ... )

2022-05-17 01:01 UTC, PouryaMansouri commented
@likecodingloveproblems please check this request too.

2022-05-17 11:11 UTC, likecodingloveproblems commented on nakhll_market/api.py
> +        self.check_object_permissions(request, shop)
:laughing:

2022-05-17 11:12 UTC, likecodingloveproblems commented on nakhll_market/models.py
> +        if Product.objects.filter(Title=self.Title, FK_Shop_id=self.FK_Shop_id).exist():
OK, please set it up with our style document in README

2022-05-17 11:13 UTC, likecodingloveproblems approved these changes

2022-05-17 11:13 UTC, merged